"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _antigravity_dashboard_shell from './antigravity-dashboard-shell.bones.json'

registerBones({
  "antigravity-dashboard-shell": _antigravity_dashboard_shell,
})
